/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tao_firstndk_Cryptor */

#ifndef _Included_com_tao_firstndk_Cryptor
#define _Included_com_tao_firstndk_Cryptor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tao_firstndk_Cryptor
 * Method:    crypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tao_firstndk_Cryptor_crypt
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     com_tao_firstndk_Cryptor
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_tao_firstndk_Cryptor_decrypt
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
